# Generated by Django 5.0.2 on 2024-03-06 15:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_product_custmor_order_orderitem_shippingadress'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='shippingadress',
            name='city',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='shippingadress',
            name='data_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='shippingadress',
            name='name',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='shippingadress',
            name='shiping_adress',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='shippingadress',
            name='state',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='shippingadress',
            name='zipcode',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='complete',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='shippingadress',
            name='custmor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.custmor'),
        ),
        migrations.AlterField(
            model_name='shippingadress',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.order'),
        ),
    ]
