# Generated by Django 5.0.2 on 2024-03-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_product_image_shippingadress_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isauser',
            field=models.BooleanField(default=True),
        ),
    ]
