# Generated by Django 5.0.2 on 2024-03-13 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_shop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='data',
        ),
        migrations.DeleteModel(
            name='figure',
        ),
    ]
